# Site settings
title: Samhi Mitra
email: samhi.mitra@gmail.com
description: > # keep this and put description below
  Programmer and Sound Designer
url: "https://samhimit.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/samhi"
github_username: samhimit
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
